---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 1
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: mariemayadi/stagebackend:latest
          ports:
            - containerPort: 8082
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address
              value: mysql
            - name: DB_NAME  # Setting Database name
              value: cloudb
            - name: DB_USERNAME  # Setting Database username
              value: root
            - name: DB_PASSWORD # Setting Database password
              value: root
# This seperator --- below is MANDATORY!!!
---

