# Define a 'Service' To Expose the application
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: default
spec:
  ports:
    - protocol: "TCP"
      port: 8082    # Port inside the cluster
      targetPort:   # Port exposed to the outside
  selector:
    app: spring
  type: NodePort

